
import time
from netCDF4 import Dataset
from oceansar.ocs_io import NETCDFHandler


class L1bFile(NETCDFHandler):
    """ Processed raw data file generated by the OASIS Simulator

        :param file_name: File name
        :param mode: Access mode (w = write, r = read, r+ = read + append)
        :param data_dim: Processed raw data dimensions
        :param format: netCDF format

        .. note::
            Refer to netCDF4 Python library for details on access mode and
            available formats
    """
    def __init__(self, file_name, mode, data_dim=None, format='NETCDF4'):

        self.__file__ = Dataset(file_name, mode, format)

        # If writing, define file
        if mode == 'w':
            # Set file attributes
            self.__file__.description = 'OCEANSAR InSAR L1b data file'
            self.__file__.history = 'Created ' + time.ctime(time.time())
            self.__file__.source = 'OCEANSAR Simulator'

            # Dimensions
            if not data_dim:
                raise ValueError('Processed raw data dimensions are needed when creating a new file!')

            self.__file__.createDimension('ch_dim', data_dim[0])
            self.__file__.createDimension('pol_dim', data_dim[1])
            self.__file__.createDimension('az_dim', data_dim[2])
            self.__file__.createDimension('rg_dim', data_dim[3])
            tot_chan = data_dim[0] * data_dim[1]
            # This is a bit complicated becasue I don't want to store redundant elements.
            self.__file__.createDimension('covel_dim', int(tot_chan * (tot_chan - 1)/2))
            num_ch = self.__file__.createVariable('num_ch', 'i4')
            # Variables
            ml_int = self.__file__.createVariable('ml_intensity',
                                                  'f8',
                                                  ('ch_dim',
                                                   'pol_dim',
                                                   'az_dim',
                                                   'rg_dim'))
            ml_coh = self.__file__.createVariable('ml_coherence',
                                                  'f8',
                                                  ('covel_dim',
                                                   'az_dim',
                                                   'rg_dim'))
            ml_phase = self.__file__.createVariable('ml_phase',
                                                    'f8',
                                                    ('covel_dim',
                                                     'az_dim',
                                                     'rg_dim'))
            coh_lut = self.__file__.createVariable('coh_lut',
                                                    'i4',
                                                    ('ch_dim',
                                                     'pol_dim',
                                                     'ch_dim',
                                                      'pol_dim'))
            ml_int.units = 'm2/m2'
            ml_phase.units = 'rad'
            coh_lut.description = "LUT that indicates where to find coh and phase for any combination\
                                   in ml_coh and ml_phase"
            inc_angle = self.__file__.createVariable('inc_angle', 'f8')
            inc_angle.units = '[deg]'
            f0 = self.__file__.createVariable('f0', 'f8')
            f0.units = '[Hz]'
            az_sampling = self.__file__.createVariable('az_sampling', 'f8')
            az_sampling.units = '[Hz]'
            v_ground = self.__file__.createVariable('v_ground', 'f8')
            v_ground.units = '[m/s]'
            orbit_alt = self.__file__.createVariable('orbit_alt', 'f8')
            orbit_alt.units = '[m]'
            sr0 = self.__file__.createVariable('sr0', 'f8')
            sr0.units = '[m]'
            rg_sampling = self.__file__.createVariable('rg_sampling', 'f8')
            rg_sampling.units = '[Hz]'
            # rg_bw = self.__file__.createVariable('rg_bw', 'f8')
            # rg_bw.units = '[Hz]'
            b_ati = self.__file__.createVariable('b_ati', 'f8', 'ch_dim')
            b_ati.units = '[m]'
            b_xti = self.__file__.createVariable('b_xti', 'f8', 'ch_dim')
            b_xti.units = '[m]'
